### PR TITLE
improved the configuration

### PR DESCRIPTION
**Pull request by mabels**
This change enable nora to configure so that nora is able to run against my own
firebase account.

### CODE REVIEW

**Comment by andrei-tatar** [comment]
@mabels Thanks for the contribution! Looks good so far.
Please leave the trailing commas as it's less lines changed when adding/removing a parameter to a function.
After that it can be merged.

**Comment by mabels** [comment]
@andrei-tatar i will try to add this to the prettier config

**Comment by mabels** [comment]
Prettier does not have an option for single argument function defintions with a trailing comma.
So i did it by hand.
But i would recommend to rething this convention.

**Comment by andrei-tatar** [comment]
I merged the PR but nora wasn't working anymore so I removed the commit.

**Comment by mabels** [comment]
> I merged the PR but nora wasn't working anymore so I removed the commit.

Hi, that's could be the case. I tried to be compatible but there could be something wrong, but without your configuration i can't test it. So I need your help to fix the raised problems.

Interessing in the first place are: 
    /login/init.js
Did you copy html after you applied the patch?

And please do not mixup this with the 3rd party cookie problems which I seeing currently with nora and actual chrome version.
```
A cookie associated with a resource at http://google.com/ was set with `SameSite=None` but without `Secure`. A future release of Chrome will only deliver cookies marked `SameSite=None` if they are also marked `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5633521622188032.
/signin/oauth/oauthchooseaccount?hl=en&client_id=461855368603-se79serkn5s5696g22ks17okv2odpkt0.apps.googleusercontent.com&as=gB6uM8E3wRtmrA20o5RZaA&destination=https%3A%2F%2Fmam-home.firebaseapp.com&approval_state=!ChRsMFJ5d0RSRlRQNG4zVHN1SS0wWBIfd3hoZDA2ZWtDZWdjY0t0V0xtY192ZG80RHo1OF9oWQ%E2%88%99AJDr988AAAAAXjBcu3DgIb8MdfTxO0kAnBtuMVrKsnB8&oauthgdpr=1&xsrfsig=ChkAeAh8T3Ma6NBE2bELKLfxl2yc5QmrshJeEg5hcHByb3ZhbF9zdGF0ZRILZGVzdGluYXRpb24SBXNvYWN1Eg9vYXV0aHJpc2t5c2NvcGU&flowName=GeneralOAuthFlow:1 A cookie associated with a cross-site resource at http://youtube.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
/signin/oauth/oauthchooseaccount?hl=en&client_id=461855368603-se79serkn5s5696g22ks17okv2odpkt0.apps.googleusercontent.com&as=gB6uM8E3wRtmrA20o5RZaA&destination=https%3A%2F%2Fmam-home.firebaseapp.com&approval_state=!ChRsMFJ5d0RSRlRQNG4zVHN1SS0wWBIfd3hoZDA2ZWtDZWdjY0t0V0xtY192ZG80RHo1OF9oWQ%E2%88%99AJDr988AAAAAXjBcu3DgIb8MdfTxO0kAnBtuMVrKsnB8&oauthgdpr=1&xsrfsig=ChkAeAh8T3Ma6NBE2bELKLfxl2yc5QmrshJeEg5hcHByb3ZhbF9zdGF0ZRILZGVzdGluYXRpb24SBXNvYWN1Eg9vYXV0aHJpc2t5c2NvcGU&flowName=GeneralOAuthFlow:1 A cookie associated with a cross-site resource at https://youtube.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
/signin/oauth/oauthchooseaccount?hl=en&client_id=461855368603-se79serkn5s5696g22ks17okv2odpkt0.apps.googleusercontent.com&as=gB6uM8E3wRtmrA20o5RZaA&destination=https%3A%2F%2Fmam-home.firebaseapp.com&approval_state=!ChRsMFJ5d0RSRlRQNG4zVHN1SS0wWBIfd3hoZDA2ZWtDZWdjY0t0V0xtY192ZG80RHo1OF9oWQ%E2%88%99AJDr988AAAAAXjBcu3DgIb8MdfTxO0kAnBtuMVrKsnB8&oauthgdpr=1&xsrfsig=ChkAeAh8T3Ma6NBE2bELKLfxl2yc5QmrshJeEg5hcHByb3ZhbF9zdGF0ZRILZGVzdGluYXRpb24SBXNvYWN1Eg9vYXV0aHJpc2t5c2NvcGU&flowName=GeneralOAuthFlow:1 A cookie associated with a cross-site resource at http://accounts.youtube.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
```

Meno

**Pull request merged**
